---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-bear-cm
  labels:
    name: dov-bear-cm
    dept: eng
data:
  INSTANCE_NAME: k8s dob-bear configmap

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-bear-secret
  labels:
    name: dov-bear-secret
    dept: eng
type: Opaque
data:
  INSTANCE_NAME: azhzIGRvYi1iZWFyIHNlY3JldA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
        dept: eng
    spec:
      volumes: 
      - name: cm-vol
        configMap:
          name: my-cm
      - name: my-pvc-vol
        persistentVolumeClaim: 
          claimName: my-vol
      containers: 
      - name: dov-bear-container
        image: chukmunnlee/dov-bear:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: cm-vol
            mountPath: /opt/configmap
            readOnly: true
          - name: my-pvc-vol
            mountPath: /opt/myvol
        envFrom:
          - secretRef: 
              name: dov-bear-secret
        ports:
          - name: dov-port
            containerPort: 3000
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 3000
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels: 
    name: dov-bear-svc
spec:
  # type: ClusterIP
  # type: NodePort (seldom use)
  type: LoadBalancer
  selector: 
    name: dov-bear-po
  ports:
    - port: 80
      targetPort: dov-port

