---
apiVersion: v1
kind: Secret
metadata:
  name: wpdbcluster-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wpdbcluster-mysql
  labels:
    name: wpdbcluster-mysql
spec:
  replicas: 3
  secretName: wpdbcluster-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: wpdb
spec:
  database: wpdb
  clusterRef:
    name: wpdbcluster-mysql
    namespace: wpns